name: Jest Tests on Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Jest Tests (TDD Mode)
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test -- --coverage