name: Linting on Feature Branches

on:
  push:
    branches:
      - "feat/**"

jobs:
  tests:
    name: ESLint Linting
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint .
